### first stage
FROM node:14-slim

WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build 

### Copy into a secondary Caddy stage

## second stage
FROM 2.1.1-alpine