version: "3"
services:
  react-app:
    image: react-app-production
    restart: unless-stopped # docker will try to restart the container for us
    stdin_open: true
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - mern-app
  api-server:
    image: api-server-production
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - mern-app
 
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local